baseURL = "https://jorshuare.github.io/josh-dev/"

languageCode = "en-us"
title = "Josh Dev"
theme = "PaperMod"

[params]
  author = "Josh"
  description = "A Software technology student documenting the journey."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  Summary = false 
  ShowToc = true 
  TocOpen = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  hideSummary = true

[params.homeInfoParams]
  Title = "Hi, I'm Joshua"
  Content = "Space Technology student. Writing about what I learn."

[[menu.main]]
  name = "About"
  url =  "/posts/about_me/"
  weight = 10

[[menu.main]]
  name = "Assignment 1"
  url = "/posts/assignment-1-report/"
  weight = 20

[[menu.main]]
  name = "Assignment 1 PDF"
  url = "/posts/assignment1pdf/"
  weight = 25

[[menu.main]]
  name = "Assignment 2"
  url = "/posts/assignment-2-report/"
  weight = 26
